version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    # 使用 build: . 从本地构建，或者使用 image: freqtradeorg/freqtrade:develop 使用开发版本
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      backtesting
      --config /freqtrade/user_data/config.json
      --strategy DS_Green_5m
      --timeframe 5m
      --timerange 20240101-
      --breakdown month
      --enable-position-stacking
      -v
